#!/bin/bash

ln -nsf ~/.local/share/dotfiles/config/zsh/alias.zsh ~/.oh-my-zsh/custom/
ln -nsf ~/.local/share/dotfiles/config/zsh/envs.zsh ~/.oh-my-zsh/custom/
ln -nsf ~/.local/share/dotfiles/config/ghostty/config ~/.config/ghostty/
ln -nsf ~/.local/share/dotfiles/config/kde/kglobalshortcutsrc ~/.config/
